# Generated by Django 5.1.2 on 2024-10-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_phoneotp_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
